apiVersion: v1
kind: Pod
metadata:
  name: nginx-a
  labels:
    podGroup: "A"
    minAvailable: "3"
spec:
  schedulerName: my-scheduler
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "100Mi"

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-b
  labels:
    podGroup: "A"
    minAvailable: "3"
spec:
  schedulerName: my-scheduler
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "100Mi"

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-c
  labels:
    podGroup: "A"
    minAvailable: "3"
spec:
  schedulerName: my-scheduler
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "100Mi"

---
